set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION r44)
set(CMAKE_SYSTEM_PROCESSOR arm-eabi)

set(DEVKITARM $ENV{DEVKITARM})
set(DEVKITPRO $ENV{DEVKITPRO})

message(STATUS "DEVKITARM: ${DEVKITARM}/bin")

if(NOT DEVKITARM)
    message(FATAL_ERROR "Please set DEVKITARM in your environment")
endif()

set(PREFIX arm-none-eabi)

find_program(CMAKE_C_COMPILER NAMES ${PREFIX}-gcc PATHS ${DEVKITARM}/bin NO_DEFAULT_PATH)
find_program(CMAKE_CXX_COMPILER NAMES ${PREFIX}-g++ PATHS ${DEVKITARM}/bin NO_DEFAULT_PATH)
find_program(CMAKE_OBJCOPY NAMES ${PREFIX}-objcopy PATHS ${DEVKITARM}/bin NO_DEFAULT_PATH)
find_program(CMAKE_OBJDUMP NAMES ${PREFIX}-objdump PATHS ${DEVKITARM}/bin NO_DEFAULT_PATH)
find_program(CMAKE_LINKER NAMES ${PREFIX}-ld PATHS ${DEVKITARM}/bin NO_DEFAULT_PATH)
find_program(CMAKE_STRIP NAMES ${PREFIX}-strip PATHS ${DEVKITARM}/bin NO_DEFAULT_PATH)

set(CMAKE_FIND_ROOT_PATH ${DEVKITARM})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_LIBRARY_PREFIXES lib)
set(CMAKE_FIND_LIBRARY_SUFFIXES .a)

include_directories(${DEVKITPRO}/libnds/include)
link_directories(${DEVKITPRO}/libnds/lib)